import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import { Providers } from "./provider";

const fontSans  = Inter({ subsets: ["latin"], variable: "--font-sans", });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IProps {
  children: React.ReactNode;
  session: any;
}

export default function RootLayout({
  children,
  session
}: IProps) {
  return (
    <html lang="pt-BR">
      <body className={cn(
          "min-h-screen bg-slate-900 text-slate-50 font-sans antialiased",
          fontSans.variable
        )}>
          <Providers>{children}</Providers>
          <Toaster />
        </body>
    </html>
  );
}
